AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description:
  gradpath-sam

  SAM Template for Gradpath SIS Back-End
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Api:
    Cors:
      AllowMethods: "'OPTIONS,POST,GET'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
  Function:
    Timeout: 25
    Environment:
      Variables:
        REGION: 'us-east-2'

Resources:
  Index:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      PackageType: Zip
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
    #Metadata:
    #  DockerTag: nodejs14.x-v1
    #  DockerContext: ./src
    #  Dockerfile: Dockerfile

  GradpathGetCourse:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/api/course/Course-GET-CourseByID
      Handler: index.lambdaHandler
      Runtime: nodejs14.x
      Policies: AmazonDynamoDBReadOnlyAccess
      PackageType: Zip
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /courses/{id}
            Method: get
    #Metadata:
    #  DockerTag: nodejs14.x-v1
    #  DockerContext: ./src/api/course/Course-GET-CourseByID
    #  Dockerfile: Dockerfile

  GradpathAddCourse:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/api/course/Course-POST-CreateNewCourse
      Handler: index.lambdaHandler
      Runtime: nodejs14.x
      Policies: AmazonDynamoDBFullAccess
      PackageType: Zip
      ImageConfig:
        Command: [ "index.lambdaHandler1" ]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /courses
            Method: post
    #Metadata:
    #  DockerTag: nodejs14.x-v1
    #  DockerContext: ./src/api/course/Course-POST-CreateNewCourse
    #  Dockerfile: Dockerfile

  # CourseTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: Course
  #     AttributeDefinitions:
  #       - AttributeName: id
  #         AttributeType: S
  #     KeySchema:
  #       - AttributeName: id
  #         KeyType: HASH
  #     ProvisionedThroughput:
  #       ReadCapacityUnits: 2
  #       WriteCapacityUnits: 1


