AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  gradpath-sam

  SAM Template for Gradpath SIS Back-End
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Api:
    Cors:
      AllowMethods: "'OPTIONS,POST,GET'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
  Function:
    Timeout: 3
    Environment:
      Variables:
        REGION: 'us-east-2'

Resources:
  Index:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: app.handler
      Runtime: nodejs14.x
      Policies: AmazonDynamoDBReadOnlyAccess
      PackageType: Image
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: ./src
      Dockerfile: Dockerfile
  GradpathGetAllCourses:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/api/course/Course-GET-ReadAllCourses
      Handler: index.handler
      Runtime: nodejs14.x
      Policies: AmazonDynamoDBReadOnlyAccess
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /courses/{id}
            Method: get
    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: ./src
      Dockerfile: Dockerfile
  GradpathAddCourse:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/api/course/Course-POST-CreateNewCourse
      Handler: index.handler
      Runtime: nodejs14.x
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /courses
            Method: post
    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: ./src
      Dockerfile: Dockerfile
  CourseTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Course
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 1


