AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description:
  gradpath-sam

  SAM Template for Gradpath SIS + LMS Back-End
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Api:
    Cors:
      AllowMethods: "'OPTIONS,POST,GET'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
  Function:
    Timeout: 25
    Environment:
      Variables:
        REGION: 'us-east-2'

Resources:
  GradpathGetCourse:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/api/course/Course-GET-CourseByID
      Handler: index.lambdaHandler
      Runtime: nodejs14.x
      Policies: AmazonDynamoDBReadOnlyAccess
      PackageType: Zip
      ImageConfig:
        Command: [ "index.lambdaHandler1" ]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /courses/{id}
            Method: get

  GradpathAddCourse:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/api/course/Course-POST-CreateNewCourse
      Handler: index.lambdaHandler
      Runtime: nodejs14.x
      Policies: AmazonDynamoDBFullAccess
      PackageType: Zip
      ImageConfig:
        Command: [ "index.lambdaHandler2" ]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /courses
            Method: post


