version: '3.8'
services:
  gradpath_db:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: gradpath_db
    networks:
      - backend
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  

networks:
  backend:
    name: gradpath

volumes:
  dynamodata: {}